#!/bin/bash
set -Eeuxo pipefail

VERSION=2.28.4
ARCHIVE="mantisbt-$VERSION.tar.gz"
URL="https://downloads.sourceforge.net/project/mantisbt/mantis-stable/$VERSION/$ARCHIVE"
SHA256=a400bd2957154baad3412130031e893d5c18cf1ed1cfb38b77ee64afd1ed2a33

proxy=()
if [[ -n ${FAB_HTTP_PROXY:-} ]]; then
    proxy=(--proxy "$FAB_HTTP_PROXY")
fi

curl --fail --location "${proxy[@]}" "$URL" \
    --output "/usr/local/src/$ARCHIVE"
printf '%s  %s\n' "$SHA256" "/usr/local/src/$ARCHIVE" |
    sha256sum --check --strict -
