#!/bin/bash -ex

DB_NAME=mantis
DB_USER=mantis
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_MAIL=admin@example.com
ADMIN_PASS=turnkey

WEBROOT=/var/www/mantis
SRC=/usr/local/src

# unpack
tar xf $SRC/mantisbt-*.tar.gz --no-same-owner -C $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/mantisbt-* $WEBROOT
rm $SRC/mantisbt-*.tar.gz

a2dissite 000-default
a2ensite mantis

chown www-data:www-data $WEBROOT
chown www-data:www-data $WEBROOT/admin

service mysql start
service apache2 start

# create DB

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# complete installation

URL="http://127.0.0.1/admin/install.php"
CURL="curl -c /tmp/cookie -b /tmp/cookie"
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
$CURL $URL --data "db_type=mysqli&hostname=localhost&db_username=$DB_USER&db_password=$DB_PASS&database_name=$DB_NAME&admin_username=&admin_password=&install=2&go=Install%2FUpgrade+Database"

# change administrator name to admin
mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
USE $DB_NAME;
UPDATE mantis_user_table SET username = '$ADMIN_NAME' WHERE id = 1;
EOF

# add settings
cat << 'EOF' >> $WEBROOT/config_inc.php

// support graphing
$g_use_jpgraph = true;
$g_jpgraph_path = "/usr/share/jpgraph/";

// integrate mantis with twitter (disabled if user is empty)
$g_twitter_username = '';
$g_twitter_password = '';
EOF

service mysql stop
service apache2 stop

rm -f /tmp/cookie
rm -rf $WEBROOT/admin

