#!/bin/bash -e
# regenerate mantis mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)
CONF=/var/www/mantis/config_inc.php

sed -i "s|db_password.*|db_password = \'$PASSWORD\';|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=mantis --pass="$PASSWORD"

