#!/bin/bash -e
# regenerate mantis mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/etc/mantis/config_db.php
sed -i "s/\$dbpass=\(.*\)/\$dbpass=\'$PASSWORD\';/" $CONF

CONF=/etc/dbconfig-common/mantis.conf
sed -i "s/dbc_dbpass=\(.*\)/dbc_dbpass=\'$PASSWORD\'/" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=mantis --pass="$PASSWORD"

